apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ksvc-endpoint-postgresql-interface
  namespace: default
spec:
  template:
    spec:
      containerConcurrency: 0
      containers:
      - image: dev.local/postgresql_interface:0.0.1
        name: user-container
        ports:
        - containerPort: 80
          protocol: TCP
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
