apiVersion: v1
kind: Service
metadata:
  name: service-endpoints-is-it-prime
spec:
  type: ClusterIP 
  selector: 
    app: is-it-prime
  ports:
  - protocol: TCP
    port: 8080
    targetPort: is-it-prime-svc 
