apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-api-gateway 
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: api_gateway:0.0.2
          imagePullPolicy: Never
          ports:
            - containerPort: 80
              name: api-gateway-svc
