apiVersion: v1
kind: Service
metadata:
  name: service-endpoints-postgresql-interface
spec:
  type: ClusterIP 
  selector: 
    app: postgresql-interface
  ports:
  - protocol: TCP
    port: 8081
    targetPort: postgresql-svc 
