apiVersion: v1
kind: Service
metadata:
  name: service-api-gateway
spec:
  type: LoadBalancer
  selector: 
    app: api-gateway
  ports:
  - protocol: TCP
    port: 8080
    targetPort: api-gateway-svc 
    nodePort: 30690
